version: "3.7"

networks:
  magizh:

services:
  db_postgres_sql:
    hostname: db_postgres_sql
    image: postgres
    networks:
      - magizh
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ../../pg_data:/var/lib/postgresql/data
  project:
    depends_on:
       - db_postgres_sql
    hostname: ecommerce
    image: magizhecommerce
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - magizh
    env_file:
      - .env
    volumes:
      - ../../logs:/home/logs
    ports:
      - "8080:8080"