server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail2mylu@gmail.com
    password: rydi bgcr aqpb owes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
magizh:
  hostname: http://localhost:3000
  stripe:
    secret:
      key: sk_test_51R6ZEGAcT2a2ILFxbzMMo7RQHg0HhjoUivuHJ52Ud8Ff6asAdxtzEzv66KeQLj2rNG9hoxGjsBebOxHTHcyZixUv00hJkvc8Sd