server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: Ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail2mylu@gmail.com
    password: rydi bgcr aqpb owes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
